services:
  postgres:
    image: postgres:15-alpine
    container_name: improve_db
    environment:
      POSTGRES_USER: improve-user
      POSTGRES_PASSWORD: improve123
      POSTGRES_DB: improve-db
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U improve-user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


