services:
  postgres:
    image: postgres:15-alpine
    container_name: improve_db
    environment:
      POSTGRES_USER: improve-user
      POSTGRES_PASSWORD: improve123
      POSTGRES_DB: improve-db
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U improve-user -d improve-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  prefect:
    image: prefecthq/prefect:3-latest
    container_name: prefect_server
    command: ["prefect", "server", "start", "--host", "0.0.0.0", "--ui"]
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://improve-user:improve123@postgres:5432/prefect_db
      PREFECT_API_URL: http://0.0.0.0:4200/api
      PREFECT_UI_SERVE_BASE: /prefect
      PREFECT_UI_API_URL: https://quiz.devwork.in/prefect/api
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  prefect_data:

